// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7x2_OQf_2scmcDjPRnq52rTalWIyyJqE',
    appId: '1:820031792770:web:e2f2f8158fd763b4fa369b',
    messagingSenderId: '820031792770',
    projectId: 'mizania-7f7c0',
    authDomain: 'mizania-7f7c0.firebaseapp.com',
    storageBucket: 'mizania-7f7c0.firebasestorage.app',
    measurementId: 'G-5513YLGCCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzLpmu5v8kZbGyf75TLql1gP5KHOdsdjk',
    appId: '1:820031792770:android:f05803951e6a48affa369b',
    messagingSenderId: '820031792770',
    projectId: 'mizania-7f7c0',
    storageBucket: 'mizania-7f7c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_PJBYcxJ-i6lDm_15lOXuX-kJjLlO5nI',
    appId: '1:820031792770:ios:f322b8ce7653cc1efa369b',
    messagingSenderId: '820031792770',
    projectId: 'mizania-7f7c0',
    storageBucket: 'mizania-7f7c0.firebasestorage.app',
    iosBundleId: 'com.example.tp5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_PJBYcxJ-i6lDm_15lOXuX-kJjLlO5nI',
    appId: '1:820031792770:ios:f322b8ce7653cc1efa369b',
    messagingSenderId: '820031792770',
    projectId: 'mizania-7f7c0',
    storageBucket: 'mizania-7f7c0.firebasestorage.app',
    iosBundleId: 'com.example.tp5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7x2_OQf_2scmcDjPRnq52rTalWIyyJqE',
    appId: '1:820031792770:web:42e092a1be346761fa369b',
    messagingSenderId: '820031792770',
    projectId: 'mizania-7f7c0',
    authDomain: 'mizania-7f7c0.firebaseapp.com',
    storageBucket: 'mizania-7f7c0.firebasestorage.app',
    measurementId: 'G-3DTL27WBQ8',
  );
}
